conormckenzie/fix OneTimeSetup
conormckenzie/reasoning-engine pull request #11
Opened 2024-08-23 23:02 UTC by conormckenzie

Fix one-time setup and integrate into program,
Bring in commits meant for dev but merged to main
Add documentation: Readme.md (improved), Contributing.md

- **Add issues.md, remove TODO from Program.cs, fix tests to pass.**
- **Fix one-time setup**
- **Add issues.md, remove TODO from Program.cs, fix tests to pass.**
- **Temporary merge of different Readme contents**
- **Clean Readme containing messy duplicate info from merge conflict**
- **Add contributing.md; Fix escaped backticks in readme**
- **Add project structure & future development stub to README**

2024-08-25 16:06 UTC, AceJester90 requested changes
Some minor issues on README.md, other parts looks good to me. On that note, Should I also test the UnitTests?

2024-08-26 21:42 UTC, conormckenzie commented on README.md
> +### Steps to Contribute:
Good catch, thanks.

2024-08-26 21:42 UTC, conormckenzie commented on README.md
> +Welcome to the Reasoning Engine project! To get started with contributing to or reviewing the project, please check out the [`dev`](https://github.com/your-repo/repository-name/tree/dev) branch.
Good catch, thanks

2024-08-28 11:35 UTC, AceJester90 approved these changes

2024-08-28 12:45 UTC, merged