Acejester90/ConvertionToSwaggerOpenAPI
conormckenzie/reasoning-engine pull request #31
Opened 2024-11-16 07:08 UTC by AceJester90

-Converted the webserver.cs
-Deleted the debug.cs
-Added debugwritelines
-Tested the SwaggerOpenAPI UI

for linux:
   export ASPNETCORE_ENVIRONMENT=Development
   dotnet run --project ReasoningEngine
for windows powershell:
   $env:ASPNETCORE_ENVIRONMENT="Development"
   dotnet run --project ReasoningEngine

2024-11-19 22:51 UTC, conormckenzie commented
I added a proposal for changes to this branch, please see:
https://github.com/conormckenzie/reasoning-engine/tree/conormckenzie/ConversionToSwaggerOpenAPI-proposal-1

Please test this branch to see if it works for you and let me know the results.

If you accept the changes, you can apply the commits to this branch directly (I suggest using `git cherry-pick` to apply the exact commits you want to)
I tried to make it so that each of the commits handled a minimal change, except for the first one because I was trying to fix the issue of Swagger not working on my machine.

2024-11-19 23:01 UTC, conormckenzie requested changes
Please also see previous comment about proposed changes at https://github.com/conormckenzie/reasoning-engine/tree/conormckenzie/ConversionToSwaggerOpenAPI-proposal-1

2024-11-19 23:01 UTC, conormckenzie commented on <C:\git\ace\reasoning-engine>/0000/00000000/000000000000/0000000000000001.json
Please try to make sure these data files are not included in your commits.
A good way to do this is to:

First, remove them. 
If there were sensitive information in these commits then you would have to overwrite the commit and force-push it. However since that's not the case you can just add a commit that deletes these 2 data files.

Second, add an entry to the .gitignore file that matches the path or name of your data files/directories (or use an existing entry). What entry you should add/use depends on where the files are (for example, I have them under a "data" folder in the project root, so the .gitignore entry "data/" matches this folder). Whenever a file or direcctory matches a .gitignore entry, then git ignores it, so it doesn't get included in commits.

2024-11-19 23:01 UTC, conormckenzie commented on <C:\git\ace\reasoning-engine>/index.json
See other data file, same applies here.

2024-11-23 13:51 UTC, AceJester90 commented on <C:\git\ace\reasoning-engine>/0000/00000000/000000000000/0000000000000001.json
Will do, I'll resolve this conversation now.

2024-11-23 13:51 UTC, AceJester90 commented on <C:\git\ace\reasoning-engine>/index.json
Done!

2024-11-23 14:07 UTC, AceJester90 commented
Hello! the branch seems to work fine, I'll add these commits now. I have a question though, should I add the openbrowser feature or should I keep it that way? That was one of the requested of webappcomponent if I remember correctly.

2024-11-25 22:36 UTC, conormckenzie commented
> Hello! the branch seems to work fine, I'll add these commits now. I have a question though, should I add the openbrowser feature or should I keep it that way? That was one of the requested of webappcomponent if I remember correctly.

Adding the openbrowser feature is not a very high priority, I included it as a nice-to-have. I am happy with it as it is.

2024-11-25 22:38 UTC, conormckenzie approved these changes
Your commits look good, I will approve this PR.

2024-11-25 22:41 UTC, merged